encoder: 
  _target_: models.audiomae.audiomae_wrapper.AudioMAEWrapper
  ckpt_name: as-2M_pt+ft
  contextual_depth: 8

name: audio-mae_${.encoder.ckpt_name}_ctx=${.encoder.contextual_depth}
group: audio-mae