encoder: 
  _target_: models.encodec.encodec_wrapper.EncodecWrapper
  model: 48khz
  repository: ${paths.ckpt_dir}
  # segment: ${audio_length}
  overlap: 0.0

name: "encodec_48khz"
group: "encodec"
