encoder: 
  _target_: models.encodec.encoder.EncodecEncoder.encodec_model_48khz
  repository: ${paths.ckpt_dir}
  # segment: ${audio_length}
  overlap: 0.0

name: "encodec_48khz"
group: "encodec"
