encoder: 
  _target_: models.encodec.encodec_wrapper.EncodecWrapper
  model: 24khz
  repository: ${paths.ckpt_dir}
  # segment: ${audio_length}
  overlap: 0.0

name: "encodec_24khz"
group: "encodec"

