encoder: 
  _target_: models.openl3.torchopenl3_wrapper.TorchOpenL3Wrapper
  input_repr: mel256
  content_type: music
  embedding_size: 6144
  hop_size: 1.0
  center: false

name: openl3_${.encoder.input_repr}_${.encoder.content_type}_${.encoder.embedding_size}
input_repr: ${.encoder.input_repr}