encoder: 
  _target_: models.passt.passt_wrapper.PasstWrapper
  features: base
  arch: passt_s_kd_p16_128_ap486
  mode: embed_only

name: ${.encoder.arch}_${.encoder.features}_${.encoder.mode}
group: passt